Avoid comparing `this` to `NULL`
In C++, it may have been legal at some stage to allow running with
`this` set to `NULL`. This is no longer the case, as testified by G++
v6.3.0:

	error: nonnull argument 'this' compared to NULL [-Werror=nonnull-compare]

Let's just remove all those conditionals.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>